on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cache Buildozer global directory
        uses: actions/cache@v2
        with:
          path: .buildozer_global
          key: buildozer-global-${{ hashFiles('buildozer.spec') }}

      - uses: actions/cache@v2
        with:
          path: .buildozer
          key: ${{ runner.os }}-${{ steps.get-date.outputs.date }}-${{ hashFiles('buildozer.spec') }}

      - name: Install python cython version
        run: 
          python -m pip install cython==0.29.33

      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        #uses: coquepas/buildozer@v1
        id: buildozer
        with:
          command: echo y | buildozer -v android debug
          #command: buildozer android debug
          buildozer_version: stable
          #buildozer_version: master

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: ${{ steps.buildozer.outputs.filename }}
