name: Build
on:
  push:
    branches-ignore:
      - data
      - gh-pages
    tags:
      - '**'

jobs:
  # Build job. Builds app for Android with Buildozer
  build-android:
    name: Build for Android
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2


      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          #solo especificar el workdir si no está el main.py en el root
          workdir: app
          buildozer_version: stable
          #command: echo y | buildozer -v android debug

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: ${{ steps.buildozer.outputs.filename }}

       - name: Commit apk
         run: |
           git checkout data
           git config --global user.name 'coquepas'
           git config --global user.email 'coquepas@users.noreply.github.com'
           git commit -am "Automated push"
           git push



